name: Sync cert-manager images

on:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract cainjector metadata
        id: meta-cainjector
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.jetstack.cert-manager-cainjector
          tags: |
            # use custom value instead of git tag
            value=v1.13.2
      - name: Build and push cainjector image
        uses: docker/build-push-action@v6.1.0
        with:
          file: cert-manager/cainjector.Dockerfile
          context: cert-manager
          push: true
          tags: ${{ steps.meta-cainjector.outputs.tags }}
          labels: ${{ steps.meta-cainjector.outputs.labels }}
      - name: cainjector Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zjuici/mirror.jetstack.cert-manager-cainjector
          short-description: mirror of cert-manager cainjector image
          readme-filepath: ./cert-manager/cainjector.README.md
      - name: Extract controller metadata
        id: meta-controller
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.jetstack.cert-manager-controller
          tags: |
            # use custom value instead of git tag
            value=v1.13.2
      - name: Build and push controller image
        uses: docker/build-push-action@v6.1.0
        with:
          file: cert-manager/controller.Dockerfile
          context: cert-manager
          push: true
          tags: ${{ steps.meta-controller.outputs.tags }}
          labels: ${{ steps.meta-controller.outputs.labels }}
      - name: controller Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zjuici/mirror.jetstack.cert-manager-controller
          short-description: mirror of cert-manager controller image
          readme-filepath: ./cert-manager/controller.README.md
      - name: Extract webhook metadata
        id: meta-webhook
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.jetstack.cert-manager-webhook
          tags: |
            # use custom value instead of git tag
            value=v1.13.2
      - name: Build and push webhook image
        uses: docker/build-push-action@v6.1.0
        with:
          file: cert-manager/webhook.Dockerfile
          context: cert-manager
          push: true
          tags: ${{ steps.meta-webhook.outputs.tags }}
          labels: ${{ steps.meta-webhook.outputs.labels }}
      - name: webhook Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zjuici/mirror.jetstack.cert-manager-webhook
          short-description: mirror of cert-manager webhook image
          readme-filepath: ./cert-manager/webhook.README.md
