name: Publish Kubeflow Notebook Base Image

on:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/kubeflow-notebooks/base
  CACHE_IMAGE: ${{ github.repository_owner }}/kubeflow-notebooks/build-cache
  CACHE_TAG: base

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # `docker/metadata-action` does this for us, but the `cache-from` and `cache-to` inputs directly read env and are cursed.
      # See this long discussion: <https://github.com/orgs/community/discussions/25768>
      - id: lower-repo
        run: |
          echo "CACHE_IMAGE=${CACHE_IMAGE@L}" >> ${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: kubeflow/kubeflow
          fetch-tags: true
          ref: refs/tags/v1.10.0
          sparse-checkout: |
            components/example-notebook-servers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # semver has default priority 900, sha has default priority 100
          # ref has default priority 600
          # see <https://github.com/docker/metadata-action#priority-attribute>
          # also, sha has a default prefix of '-sha'
          # see <https://github.com/docker/metadata-action#typesha>
          tags: |
            type=semver,pattern={{version}}
            type=sha,priority=850,prefix=
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.18.0
        with:
          file: components/example-notebook-servers/base/Dockerfile
          context: components/example-notebook-servers/base
          # Do not upgrade to Ubuntu 23.04 or newer — it introduces a default 'ubuntu' user (UID 1000),
          # which conflicts with the NB_UID in the base image. NB_UID is defined via ENV, not ARG,
          # so we can't override it at build time.
          # Safe to upgrade once this PR is merged: https://github.com/kubeflow/kubeflow/pull/7728
          build-args: |
            BASE_IMG=ubuntu:22.04
            S6_VERSION=v3.2.1.0
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_IMAGE }}:${{ env.CACHE_TAG }}
          # See <https://docs.docker.com/build/cache/backends/#cache-mode>
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_IMAGE }}:${{ env.CACHE_TAG }},mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
