name: Publish Kubeflow Notebook Code Server Python Image

on:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/kubeflow-notebooks/codeserver-python
  BASE_IMAGE: ${{ github.repository_owner }}/kubeflow-notebooks/codeserver:4d048ea
  CACHE_IMAGE: ${{ github.repository_owner }}/kubeflow-notebooks/build-cache
  CACHE_TAG: codeserver-python

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # `docker/metadata-action` does this for us, but the `cache-from` and `cache-to` inputs directly read env and are cursed.
      # See this long discussion: <https://github.com/orgs/community/discussions/25768>
      - id: lower-repo
        run: |
          echo "BASE_IMAGE=${BASE_IMAGE@L}" >> ${GITHUB_ENV}
          echo "CACHE_IMAGE=${CACHE_IMAGE@L}" >> ${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: kubeflow/kubeflow
          fetch-tags: true
          ref: refs/tags/v1.10.0
          sparse-checkout: |
            components/example-notebook-servers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # semver has default priority 900, sha has default priority 100
          # ref has default priority 600
          # see <https://github.com/docker/metadata-action#priority-attribute>
          # also, sha has a default prefix of '-sha'
          # see <https://github.com/docker/metadata-action#typesha>
          tags: |
            type=semver,pattern={{version}}
            type=sha,priority=850,prefix=
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.16.0
        with:
          file: components/example-notebook-servers/codeserver-python/Dockerfile
          context: components/example-notebook-servers/codeserver-python
          # CODESERVER_PYTHON_VERSION: codeserver python plugin version
          # See <https://open-vsx.org/extension/ms-python/python>
          # CODESERVER_JUPYTER_VERSION: codeserver jupyter plugin version
          # See <https://open-vsx.org/extension/ms-toolsai/jupyter>
          # Note that there's a "Works With" section on the page that indicates the VS Code version.
          # IPYKERNEL_VERSION: <https://github.com/ipython/ipykernel/releases>
          # MINIFORGE_VERSION: <https://github.com/conda-forge/miniforge/releases>
          build-args: |
            BASE_IMG=${{ env.REGISTRY }}/${{ env.BASE_IMAGE }}
            CODESERVER_PYTHON_VERSION=2025.4.0
            CODESERVER_JUPYTER_VERSION=2025.3.0
            IPYKERNEL_VERSION=6.29.5
            MINIFORGE_VERSION=24.11.3-2
            PIP_VERSION=25.1.1
            PYTHON_VERSION=3.13.3
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_IMAGE }}:${{ env.CACHE_TAG }}
          # See <https://docs.docker.com/build/cache/backends/#cache-mode>
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_IMAGE }}:${{ env.CACHE_TAG }},mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
