name: Sync knative-serving images

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  sync-knative-serving-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract activator metadata
        id: meta-activator
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.knative-serving.serving-core.activator
          tags: |
            # use custom value instead of git tag
            value=v1.12.3
      - name: Build and push activator image
        uses: docker/build-push-action@v5.1.0
        with:
          file: knative/serving/serving-core/activator.Dockerfile
          context: knative/serving/serving-core  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-activator.outputs.tags }}
          labels: ${{ steps.meta-activator.outputs.labels }}
      - name: Extract autoscaler metadata
        id: meta-autoscaler
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.knative-serving.serving-core.autoscaler
          tags: |
            # use custom value instead of git tag
            value=v1.12.3
      - name: Build and push autoscaler image
        uses: docker/build-push-action@v5.1.0
        with:
          file: knative/serving/serving-core/autoscaler.Dockerfile
          context: knative/serving/serving-core  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-autoscaler.outputs.tags }}
          labels: ${{ steps.meta-autoscaler.outputs.labels }}
      - name: Extract controller metadata
        id: meta-controller
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.knative-serving.serving-core.controller
          tags: |
            # use custom value instead of git tag
            value=v1.12.3
      - name: Build and push controller image
        uses: docker/build-push-action@v5.1.0
        with:
          file: knative/serving/serving-core/controller.Dockerfile
          context: knative/serving/serving-core  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-controller.outputs.tags }}
          labels: ${{ steps.meta-controller.outputs.labels }}
      - name: Extract queue metadata
        id: meta-queue
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.knative-serving.serving-core.queue
          tags: |
            # use custom value instead of git tag
            value=v1.12.3
      - name: Build and push queue image
        uses: docker/build-push-action@v5.1.0
        with:
          file: knative/serving/serving-core/queue.Dockerfile
          context: knative/serving/serving-core  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-queue.outputs.tags }}
          labels: ${{ steps.meta-queue.outputs.labels }}
      - name: Extract webhook metadata
        id: meta-webhook
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.knative-serving.serving-core.webhook
          tags: |
            # use custom value instead of git tag
            value=v1.12.3
      - name: Build and push webhook image
        uses: docker/build-push-action@v5.1.0
        with:
          file: knative/serving/serving-core/webhook.Dockerfile
          context: knative/serving/serving-core  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-webhook.outputs.tags }}
          labels: ${{ steps.meta-webhook.outputs.labels }}
      - name: Extract net-istio/controller metadata
        id: meta-net-istio-controller
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.knative-serving.net-istio.controller
          tags: |
            # use custom value instead of git tag
            value=v1.12.1
      - name: Build and push net-istio/controller image
        uses: docker/build-push-action@v5.1.0
        with:
          file: knative/serving/net-istio/controller.Dockerfile
          context: knative/serving/net-istio  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-net-istio-controller.outputs.tags }}
          labels: ${{ steps.meta-net-istio-controller.outputs.labels }}
      - name: Extract net-istio/webhook metadata
        id: meta-net-istio-webhook
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.knative-serving.net-istio.webhook
          tags: |
            # use custom value instead of git tag
            value=v1.12.1
      - name: Build and push net-istio/webhook image
        uses: docker/build-push-action@v5.1.0
        with:
          file: knative/serving/net-istio/webhook.Dockerfile
          context: knative/serving/net-istio  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-net-istio-webhook.outputs.tags }}
          labels: ${{ steps.meta-net-istio-webhook.outputs.labels }}
