name: Sync llama.cpp image

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for server image
        id: meta-server
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.ggerganov.llama.cpp
          tags: |
            # use custom value instead of git tag
            value=server--b1-3814a07
      - name: Build and push server Docker image
        uses: docker/build-push-action@v5.2.0
        with:
          file: llama.cpp/server/Dockerfile
          context: llama.cpp/server  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
      - name: Extract metadata (tags, labels) for server-cuda image
        id: meta-server-cuda
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.ggerganov.llama.cpp
          tags: |
            # use custom value instead of git tag
            value=server-cuda--b1-3814a07
      - name: Build and push server-cuda Docker image
        uses: docker/build-push-action@v5.2.0
        with:
          file: llama.cpp/server-cuda/Dockerfile
          context: llama.cpp/server-cuda  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-server-cuda.outputs.tags }}
          labels: ${{ steps.meta-server-cuda.outputs.labels }}
