name: Sync prometheus-operator images

on:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract prometheus-operator metadata
        id: meta-prometheus-operator
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.prometheus-operator.prometheus-operator
          tags: |
            # use custom value instead of git tag
            value=v0.67.1
      - name: Build and push prometheus-operator image
        uses: docker/build-push-action@v6.4.1
        with:
          file: prometheus-operator/prometheus-operator.Dockerfile
          context: prometheus-operator
          push: true
          tags: ${{ steps.meta-prometheus-operator.outputs.tags }}
          labels: ${{ steps.meta-prometheus-operator.outputs.labels }}
      - name: Extract prometheus-config-reloader metadata
        id: meta-prometheus-config-reloader
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.prometheus-operator.prometheus-config-reloader
          tags: |
            # use custom value instead of git tag
            value=v0.67.1
      - name: Build and push prometheus-config-reloader image
        uses: docker/build-push-action@v6.4.1
        with:
          file: prometheus-operator/prometheus-config-reloader.Dockerfile
          context: prometheus-operator
          push: true
          tags: ${{ steps.meta-prometheus-config-reloader.outputs.tags }}
          labels: ${{ steps.meta-prometheus-config-reloader.outputs.labels }}
