name: Sync huggingface/text-embeddings-inference images

on:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # cpu image
      - name: Extract CPU image metadata
        id: meta-cpu
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=cpu-1.2.2
      - name: Build and push CPU image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile.cpu
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-cpu.outputs.tags }}
          labels: ${{ steps.meta-cpu.outputs.labels }}
      # cpu grpc image
      - name: Extract CPU grpc image metadata
        id: meta-cpu-grpc
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=cpu-1.2.2-grpc
      - name: Build and push CPU grpc image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile.cpu-grpc
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-cpu-grpc.outputs.tags }}
          labels: ${{ steps.meta-cpu-grpc.outputs.labels }}
      # amphere 80 image
      - name: Extract Amphere 80 image metadata
        id: meta-amphere80
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=1.2.2
      - name: Build and push Amphere 80 image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-amphere80.outputs.tags }}
          labels: ${{ steps.meta-amphere80.outputs.labels }}
      # amphere 80 grpc image
      - name: Extract Amphere 80 grpc image metadata
        id: meta-amphere80-grpc
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=1.2.2-grpc
      - name: Build and push Amphere 80 grpc image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile-grpc
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-amphere80-grpc.outputs.tags }}
          labels: ${{ steps.meta-amphere80-grpc.outputs.labels }}
      # amphere 86 image
      - name: Extract Amphere 86 image metadata
        id: meta-amphere86
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=86-1.2.2
      - name: Build and push Amphere 86 image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile.86
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-amphere86.outputs.tags }}
          labels: ${{ steps.meta-amphere86.outputs.labels }}
      # amphere 86 grpc image
      - name: Extract Amphere 86 grpc image metadata
        id: meta-amphere86-grpc
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=86-1.2.2-grpc
      - name: Build and push Amphere 86 grpc image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile.86-grpc
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-amphere86-grpc.outputs.tags }}
          labels: ${{ steps.meta-amphere86-grpc.outputs.labels }}
      # amphere 89 image
      - name: Extract Amphere 89 image metadata
        id: meta-amphere89
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=89-1.2.2
      - name: Build and push Amphere 89 image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile.89
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-amphere89.outputs.tags }}
          labels: ${{ steps.meta-amphere89.outputs.labels }}
      # amphere 89 grcp image
      - name: Extract Amphere 89 grcp image metadata
        id: meta-amphere89-grcp
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-embeddings-inference
          tags: |
            # use custom value instead of git tag
            value=89-1.2.2-grpc
      - name: Build and push Amphere 89 grcp image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-embeddings-inference/Dockerfile.89-grcp
          context: huggingface/text-embeddings-inference # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta-amphere89-grcp.outputs.tags }}
          labels: ${{ steps.meta-amphere89-grcp.outputs.labels }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zjuici/mirror.huggingface.text-embeddings-inference
          short-description: mirror of huggingface text-embeddings-inference image
          readme-filepath: ./huggingface/text-embeddings-inference/README.md
