name: Sync huggingface/text-generation-inference image

on:
  # This image is too large and causes 'No space left on device' error on github's workflow runner
  # Unless we have our own runner, we cannot use this workflow
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: zjuici/mirror.huggingface.text-generation-inference
          tags: |
            # use custom value instead of git tag
            type=semver,pattern={{version}},value=v2.0.1
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          file: huggingface/text-generation-inference/Dockerfile
          context: huggingface/text-generation-inference  # context does not matter not as there are no files
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
